import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-slate-800 font-sans">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="relative container mx-auto p-6 ">
        <nav className="flex items-center justify-between">
          <img src="logo.jpg" alt="logo" className="h-[80px] w-[8 0px]" />
          {/* Menu items */}
          <ol className="hidden md:flex justify-between items-center space-x-6 text-mint  ">
            <li>About</li>
            <li>Projects</li>
            <li>Contact</li>
            <li>Resume</li>
          </ol>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center w-full">
        <section
          id="welcome"
          className="h-screen flex flex-col justify-start space-y-4  px-6  bg-slate-800 text-center text-slate-300  md:px-24 md:text-left lg:px-64"
        >
          <div className="flex flex-col justify-start space-y-4 container mx-auto">
            <h1 className="flex flex-col mt-28 space-y-4  text-xl font-bold  md:text-6xl">
              <span className="text-sm text-mint">Hi, my name is </span>
              <span className="text-slate-50">Antony Merle.</span>
              <span>I build apps for today's Internet.</span>
            </h1>
            <p>
              Full Stack Web Developer with a passion for crafting intuitive and
              user-friendly web experiences. My main focus is developing
              responsive and dynamic websites that engage visitors and meet
              business requirements. With 3 years of experience and a focus on
              continual learning, I am committed to delivering high-quality and
              innovative solutions.
            </p>
          </div>
        </section>

        <section id="about" className="w-full h-screen  bg-slate-50">
          <div
            id="about-container"
            className="block h-screen max-w-[900px] mx-auto bg-slate-100  "
          >
            <div
              id="about-header"
              className="w-full flex flex-row justify-center items-center md:justify-start"
            >
              <h2 className="space-x-2 py-6 text-xl font-bold  md:text-4xl">
                <span className="text-lg text-mint">01.</span>
                <span>About me</span>
              </h2>
            </div>

            <div
              id="about-inner"
              className="container md:h-auto md:grid md:gap-4 md:grid-cols-[2fr_1fr]"
            >
              <div id="about-text" className="text-center md:text-left">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Perspiciatis obcaecati ratione eum cum porro dicta soluta
                  iusto possimus cumque ullam esse, laboriosam, aliquam maxime
                  repudiandae doloremque ad magni. Impedit, molestias. Lorem
                  ipsum dolor sit amet, consectetur adipisicing elit.
                  Perspiciatis obcaecati ratione eum cum porro dicta soluta
                  iusto possimus cumque ullam esse, laboriosam, aliquam maxime
                  repudiandae doloremque ad magni. Impedit, molestias. Lorem
                  ipsum dolor sit amet, consectetur adipisicing elit.
                  Perspiciatis obcaecati ratione eum cum porro dicta soluta
                  iusto possimus cumque ullam esse, laboriosam, aliquam maxime
                  repudiandae doloremque ad magni. Impedit, molestias. Lorem
                  ipsum dolor sit amet, consectetur adipisicing elit.
                  Perspiciatis obcaecati ratione eum cum porro dicta soluta
                  iusto possimus cumque ullam esse, laboriosam, aliquam maxime
                  repudiandae doloremque ad magni. Impedit, molestias.
                </p>
              </div>
              {/*     /bg-[url('../public/antony-merle.jpg')] */}
              {/* bloc image */}
              <div className="block container  md:flex-row md:justify-start md:items-center ">
                <div id="about-picture" className="relative">
                  <div className=" block mx-auto my-10 shadow-[10px_10px_#72ECCE] object-cover h-[250px] w-[250px] bg-slate-300 md:my-0 md:z-10 md:absolute md:shadow-none">
                    <img src="antony-merle.jpg"></img>
                  </div>
                  <div className="hidden top-[20px] left-[20px] h-[250px] w-[250px] border-solid border-2  border-slate-800 md:block md:z-0 md:absolute"></div>
                </div>
              </div>
              {/* bloc image */}
            </div>
          </div>
        </section>
        <section id="projects">
          Here are a few of the projects I worked on lately.
        </section>
        <section id="contact">Let's talk.</section>
      </main>
      <footer>Antony Merle, {new Date().getFullYear()}</footer>
    </div>
  );
}
